### ISSUE TITLE
reason-cli '.tar.gz' NPM package errors on NPM update

### ISSUE THREAD

**Issue by superherointj** [reasonml/reason-cli#48]
Problem:

NPM v5.4.2 doesn't handle '.tar.gz' package format properly, on update errors and stops the update, might interfere with other extraneous packages too (but I didn't test it yet) :

On MacOS:

> MacBook-Pro:~ intj$ npm -g update
> npm ERR! code E404
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/reason-cli
> npm ERR! 404
> npm ERR! 404 'reason-cli' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/intj/.npm/_logs/2017-10-03T10_14_41_827Z-debug.log
> MacBook-Pro:~ intj$

On Ubuntu:

> intj@intjDesktop:~ $ npm -g update
> npm ERR! code E404
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/reason-cli
> npm ERR! 404
> npm ERR! 404 'reason-cli' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/intj/.npm/_logs/2017-10-03T12_35_58_630Z-debug.log
> intj@intjDesktop:~ $

Possible fix:
1 - Publish 'reason-cli' NPM package
2 - Deprecate '.tar.gz' package format

**Comment by zploskey** [comment]
I've started to try to solve this one. On discord @andreypopp suggested I create a new package that could be published to npm. Essentially I'd like it to be a script that installs the right tarball for your platform. I don't have a lot of experience on the node platform (Reason is the whole reason I'm getting involved), so any suggestions or PRs would be appreciated.

The code is here: https://github.com/zploskey/reason-cli-bin

**Comment by zploskey** [comment]
That repo is now a working prototype (for me at least). Tested on Linux. Could use a mac tester.

**Comment by csi-adziahel** [comment]
> That repo is now a working prototype (for me at least). Tested on Linux. Could use a mac tester.

@zploskey well, doesn't seem so simple anymore for 3.0.0 since the move to `esy`.

**Comment by zploskey** [comment]
Hopefully the move to esy actually solves this. I think it still needs some work, though.

**Comment by jordwalke** [comment]
`reason-cli-bin` is a good idea. Did you model it after `flow-bin`? I'm curios about what the best way to do this is. It's generally good for npm packages to not download things on postinstall, but I don't know of any other way. I don't think npm/yarn have any way to dynamically compute a package dependency based on platform. If it did I would express a dependency as something like:

```json
"dependencies": {
  "reason-cli": "platform === 'darwin' ? 'reason-cli-darwin@3.0.0' : 'reason-cli-linux@3.0.0' : 'null'"
}
```

**Comment by jordwalke** [comment]
Is the original issue still a problem?

**Comment by superherointj** [comment]
Yes, the original issue is still a problem. Npm doesn't handle .tar.gz packages gracefully on upgrades and fails affecting other packages.

**Comment by superherointj** [comment]
Give it a try. Install reason-cli and try to upgrade npm globally and see how it goes.

**Comment by zploskey** [comment]
It looks like since installing the 3.0.0 linux tarball I can do `npm update -g` with receiving an error as shown in the first post. It just downloaded a few updates and worked just fine. Unless this is somehow still a problem for anyone else, this can probably be closed.

> reason-cli-bin is a good idea. Did you model it after flow-bin?

Sort of. I looked up other npm packages that needed to distribute binaries and saw that they used -bin in their names so I followed suit.

Having a way to download pre-compiled packages for your architecture is really useful and clearly something that JS is going to need more of in the future. Python solved this problem a few years ago with what they call wheel binary packages (.whl) because having the packages be compiled on demand was too error-prone, and nearly impossible to get right on Windows. It would be great if we could get something like that to be adopted. It might be good enough for the package managers or repositories to agree on a mechanism for selecting the right binary package by architecture in the request to the repository, and the package manager could provide an override if the user wanted to get binary dependencies for another architecture in order to deploy somewhere else.

The way you suggest with substituting $platform in the name seems reasonable and fits within what's already there in package.json. If the other package managers aren't willing to do it, maybe esy should do it. If it gains traction the others may adopt it too.

**Comment by jordwalke** [comment]
" with receiving an error as "
Did you mean *without* receiving an error?

**Comment by superherointj** [comment]
Problem persists but NPM packages can still be upgraded manually/individually and without errors if done this way. It affects global upgrades only. 

Newcomers might be confused on this until they understand this. Leave this open as a reminder of this problem.

**Comment by zploskey** [comment]
@jordwalke Yes, it did not give me an error this last time I tried. Seems to still be a problem for some.

**Comment by develop7** [comment]
@jordwalke confirming 3.0.0 doesn't make the issue go away.
